### ISSUE TITLE
web-beautify-format-buffer problem

### ISSUE THREAD

**Issue by bitspook** [channikhabra/css-comb.el#2]
From Peiwen Lu (email):

I just installed your css-comb.el package and I get an issues which I am not be able to solve, so I am wondering if you mind giving me some tips. Thanks.

The css-comb.el works great without web-beautify.el installed. But after I installed web-beautify.el and call `css-comb`, I get the following error: 

css-comb-format-buffer-1: Wrong number of arguments: #[(program) "Áed#" [program web-beautify-format-region] 4 ("/Users/peiwen/.emacs.d/elpa/web-beautify-20160410.1005/web-beautify.elc" . 2362)], 2

When I firstly installed css-comb.el, I remember there is a warning message:

Warning (bytecomp): web-beautify-format-buffer called with 2 arguments, but accepts only 1

Calling `web-beautify-css` or other web-beautify commands work great. I don’t know if I need additional settings for css-comb.el.

I am currently using Emacs 25 nightly build. Would you mind giving me a little tips for that? It is really nice if I could run css-comb on Emacs.

**Comment by bitspook** [comment]
This issue should've been fixed in https://github.com/channikhabra/css-comb.el/commit/6fa45e5af8a8bd3af6c1154cde3540e32c4206ee 

Waiting for Peiwen's response to confirm the fix.

**Comment by P233** [comment]
Work like a charm. Thanks!!
